#!/bin/bash
DIR="/home/ramzel/.config/eww/scripts/ss/"
A=$(cat ${DIR}clip_o)
if [ "$A" == "yes" ]; then
	echo "no" > ${DIR}clip_o
else
	echo "yes" > ${DIR}clip_o
fi
/home/ramzel/Installs/eww/target/release/eww update ss_clip_o="$(cat ${DIR}clip_o)"
